export const siteNavLinks = [
  {
    title: 'Layout',
    links: [
      { href: '/app-shell', label: 'AppShell' },
      { href: '/aspect-ratio', label: 'AspectRatio', dimmed: true },
      { href: '/center', label: 'Center' },
      { href: '/container', label: 'Container' },
      { href: '/flex', label: 'Flex' },
      { href: '/grid', label: 'Grid' },
      { href: '/group', label: 'Group' },
      { href: '/media-query', label: 'MediaQuery', dimmed: true },
      { href: '/simple-grid', label: 'SimpleGrid' },
      { href: '/space', label: 'Space' },
      { href: '/stack', label: 'Stack' },
    ],
  },
  {
    title: 'Buttons',
    links: [
      { href: '/action-icon', label: 'ActionIcon' },
      { href: '/button', label: 'Button' },
      { href: '/close-button', label: 'CloseButton', dimmed: true },
      { href: '/copy-button', label: 'CopyButton', dimmed: true },
      { href: '/file-button', label: 'FileButton', dimmed: true },
      { href: '/unstyled-button', label: 'UnstyledButton' },
    ],
  },
  {
    title: 'Inputs',
    links: [
      { href: '/autocomplete', label: 'Autocomplete' },
      { href: '/checkbox', label: 'Checkbox' },
      { href: '/chip', label: 'Chip', dimmed: true },
      { href: '/color-input', label: 'ColorInput', dimmed: true },
      { href: '/color-picker', label: 'ColorPicker', dimmed: true },
      { href: '/file-input', label: 'FileInput', dimmed: true },
      { href: '/input', label: 'Input' },
      { href: '/json-input', label: 'JsonInput', dimmed: true },
      { href: '/multi-select', label: 'MultiSelect', dimmed: true },
      { href: '/native-select', label: 'NativeSelect' },
      { href: '/number-input', label: 'NumberInput', dimmed: true },
      { href: '/password-input', label: 'PasswordInput' },
      { href: '/pin-input', label: 'PinInput', dimmed: true },
      { href: '/radio', label: 'Radio', dimmed: true },
      { href: '/rating', label: 'Rating', dimmed: true },
      { href: '/segmented-control', label: 'SegmentedControl', dimmed: true },
      { href: '/select', label: 'Select', dimmed: true },
      { href: '/slider', label: 'Slider' },
      { href: '/switch', label: 'Switch' },
      { href: '/textarea', label: 'Textarea' },
      { href: '/text-input', label: 'TextInput' },
      { href: '/transfer-list', label: 'TransferList', dimmed: true },
    ],
  },
  {
    title: 'Navigation',
    links: [
      { href: '/anchor', label: 'Anchor' },
      { href: '/breadcrumbs', label: 'Breadcrumbs', dimmed: true },
      { href: '/burger', label: 'Burger' },
      { href: '/nav-link', label: 'NavLink', dimmed: true },
      { href: '/pagination', label: 'Pagination', dimmed: true },
      { href: '/stepper', label: 'Stepper', dimmed: true },
      { href: '/tabs', label: 'Tabs' },
    ],
  },
  {
    title: 'Data display',
    links: [
      { href: '/accordion', label: 'Accordion', dimmed: true },
      { href: '/avatar', label: 'Avatar' },
      { href: '/background-image', label: 'BackgroundImage', dimmed: true },
      { href: '/badge', label: 'Badge', dimmed: true },
      { href: '/card', label: 'Card', dimmed: true },
      { href: '/color-swatch', label: 'ColorSwatch', dimmed: true },
      { href: '/image', label: 'Image', dimmed: true },
      { href: '/indicator', label: 'Indicator', dimmed: true },
      { href: '/kbd', label: 'Kbd', dimmed: true },
      { href: '/spoiler', label: 'Spoiler', dimmed: true },
      { href: '/theme-icon', label: 'ThemeIcon', dimmed: true },
      { href: '/timeline', label: 'Timeline', dimmed: true },
    ],
  },
  {
    title: 'Overlays',
    links: [
      { href: '/affix', label: 'Affix' },
      { href: '/dialog', label: 'Dialog' },
      { href: '/drawer', label: 'Drawer' },
      { href: '/hover-card', label: 'HoverCard', dimmed: true },
      { href: '/loading-overlay', label: 'LoadingOverlay', dimmed: true },
      { href: '/menu', label: 'Menu' },
      { href: '/modal', label: 'Modal', dimmed: true },
      { href: '/overlay', label: 'Overlay', dimmed: true },
      { href: '/popover', label: 'Popover', dimmed: true },
      { href: '/tooltip', label: 'Tooltip', dimmed: true },
    ],
  },
  {
    title: 'Typography',
    links: [
      { href: '/blockquote', label: 'Blockquote', dimmed: true },
      { href: '/code', label: 'Code' },
      { href: '/highlight', label: 'Highlight', dimmed: true },
      { href: '/list', label: 'List' },
      { href: '/mark', label: 'Mark', dimmed: true },
      { href: '/table', label: 'Table' },
      { href: '/text', label: 'Text' },
      { href: '/title', label: 'Title' },
      { href: '/typography-styles-provider', label: 'TypographyStylesProvider', dimmed: true },
    ],
  },
  {
    title: 'Feedback',
    links: [
      { href: '/alert', label: 'Alert' },
      { href: '/loader', label: 'Loader' },
      { href: '/notification', label: 'Notification' },
      { href: '/notifications', label: 'Notifications' },
      { href: '/progress', label: 'Progress', dimmed: true },
      { href: '/ring-progress', label: 'RingProgress', dimmed: true },
      { href: '/skeleton', label: 'Skeleton', dimmed: true },
    ],
  },
  {
    title: 'Miscellaneous',
    links: [
      { href: '/box', label: 'Box' },
      { href: '/collapse', label: 'Collapse', dimmed: true },
      { href: '/divider', label: 'Divider', dimmed: true },
      { href: '/focus-trap', label: 'FocusTrap', dimmed: true },
      { href: '/paper', label: 'Paper' },
      { href: '/portal', label: 'Portal', dimmed: true },
      { href: '/scroll-area', label: 'ScrollArea' },
      { href: '/transition', label: 'Transition', dimmed: true },
    ],
  },
];
