import {
  Avatar,
  Container,
  Group,
  HtmlComponent,
  IconStar,
  IconUserCircle,
  Paper,
  Text,
  Title,
} from '@openlooks/core';

export class AvatarPage extends HtmlComponent {
  constructor() {
    super('div', '', undefined, undefined, {
      children: [
        new Container({
          className: 'doc-body size-sm p-sm py-xl',
          children: [
            new Title({ order: 1, text: 'Avatar' }),
            new Text({ text: 'Display user profile image, initials or fallback icon' }),
            new Title({ order: 2, text: 'Usage' }),
            new Paper({
              className: 'p-xl withBorder',
              children: [
                new Group({
                  children: [
                    new Avatar({
                      radius: 'xl',
                      src: '/avatar.webp',
                      alt: 'Generated by Midjourney',
                    }),
                    new Avatar({
                      radius: 'xl',
                      icon: new IconUserCircle({ size: '1.75rem' }),
                    }),
                    new Avatar({ color: 'cyan', radius: 'xl', text: 'MK' }),
                    new Avatar({
                      color: 'blue',
                      radius: 'sm',
                      icon: new IconStar({ size: '1.5rem' }),
                    }),
                  ],
                }),
              ],
            }),
          ],
        }),
      ],
    });
  }
}
