// Create index.ts from components list

const { writeFileSync, readdirSync } = require('node:fs');

async function main() {
  const files = [];
  getFiles('./src', files);
  files.sort(sortComparator);

  const outputLines = [];
  outputLines.push('// This file is auto-generated by buildindex.cjs');
  outputLines.push('// Do not edit this file directly');

  for (const file of files) {
    if (file.endsWith('/index.ts')) {
      continue;
    }
    outputLines.push(`export * from '${file.replace('./src/', './').replace('.ts', '')}';`);
  }

  outputLines.push('');
  writeFileSync('./src/index.ts', outputLines.join('\n'), 'utf8');
}

function getFiles(dir, output = []) {
  for (const file of readdirSync(dir, { withFileTypes: true })) {
    const res = `${dir}/${file.name}`;
    if (file.isDirectory()) {
      getFiles(res, output);
    } else {
      output.push(res);
    }
  }
}

function sortComparator(a, b) {
  const aStr = `${a.dir}/${a.file}`;
  const bStr = `${b.dir}/${b.file}`;
  return aStr.localeCompare(bStr);
}

if (require.main === module) {
  main();
}
